### ISSUE TITLE
How to change colors?

### ISSUE THREAD

**Issue by AndrewLaganaro** [gepser/markdown-progress#1]
Hello.
I have tried to put /yellow/90 and /90/yellow but got no luck

How do I change the bar colors?
Also, is blue available? Thanks!

**Comment by gepser** [comment]
Hello @AndrewLaganaro, to answer directly, is not possible.

The idea is to have the colors automatically selected depending on the progress of the bar.

For instance: from 0% to 32% = red, from 33% to 69% = yellow, and from 70% to 100% is green.
![](https://geps.dev/progress/32)
![](https://geps.dev/progress/69)
![](https://geps.dev/progress/70)

It is simple enough but I can see that selecting colors could be useful, maybe I should take some time to implement that.

Thanks for bringing that up 😊

**Comment by AndrewLaganaro** [comment]
Would be nice to have this feature unlocked to everyone to decide the colors! haha

**Comment by gepser** [comment]
Thanks for the comment @AndrewLaganaro, I implemented it following your suggestion, I hope it helps, now you can choose your colors, for example:

    ![](https://geps.dev/progress/32?dangerColor=800000&warningColor=ff9900&successColor=006600)

![](https://geps.dev/progress/32?dangerColor=800000&warningColor=ff9900&successColor=006600)
![](https://geps.dev/progress/69?dangerColor=800000&warningColor=ff9900&successColor=006600)
![](https://geps.dev/progress/70?dangerColor=800000&warningColor=ff9900&successColor=006600)

and, of course, if you don't add anything, you still get the defaults:

    ![](https://geps.dev/progress/32)

![](https://geps.dev/progress/32)
![](https://geps.dev/progress/69)
![](https://geps.dev/progress/70)

You can pick your colors from here, for example, https://www.w3schools.com/colors/colors_picker.asp.

I'll add detailed docs in the readme later, but I think you can use it from now already.
